apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260626-145120-2bi9o271cyxx-service
spec:
  selector:
    app: enterprise-system-20260626-145120-2bi9o271cyxx
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
